### ISSUE TITLE
flake.lock contains an invalid "treeHash" attribute for nixpkgs (a github: input)

### ISSUE THREAD

**Issue by delroth** [grahamc/packet-nix-builder#21]
Regression from https://github.com/NixOS/equinix-metal-builders/commit/f8bba1b8f1a4aeab414228683e9aa568d2fa90b3 causing https://hydra.nixos.org/jobset/equinix-metal-builders/main to not eval correctly anymore.

```
'nix flake metadata' returned exit code 1:
error:
       … while updating the lock file of flake 'github:NixOS/equinix-metal-builders/aeae1ffb8c1b1682913a1e7c6bc8c970b3afcfba'

       error: input attribute 'treeHash' not supported by scheme 'github'
```

I wonder if this maybe was locked with a weird version of Nix. Anyway, needs a refresh.

**Comment by cole-h** [comment]
Yep, oops, I was using lazy trees at the time. Fixed in #22.
